apiVersion: infra.k8smgmt.io/v3
kind: Namespace
metadata:
  name: new-ns
  project: testing-dileep
spec:
  limitRange:
    container: {}
    pod: {}
  namespaceMeshPolicyParams: {}
  placement:
    labels:
    - key: rafay.dev/clusterName
      value: dileep-import
  resourceQuotas: {}
