apiVersion: apps.k8smgmt.io/v3
kind: WorkloadTemplate
metadata:
  name: d-my-new-helmrepo
  project: testing-dileep
spec:
  artifact:
    artifact:
      chartName: app
      chartVersion: 0.1.21
      repository: my-latest-git-helm
    options:
      maxHistory: 10
      timeout: 5m0s
    type: Helm
