apiVersion: apps.k8smgmt.io/v3
kind: Workload
metadata:
  name: d-my-new-helmrepo-de2b0cb0
  project: testing-dileep
spec:
  artifact:
    artifact:
      chartName: app
      chartVersion: 0.1.22
      repository: my-latest-git-helm
    options:
      maxHistory: 10
      timeout: 5m0s
    type: Helm
  namespace: test-ns
  placement:
    labels:
    - key: rafay.dev/clusterName
      value: dileep-import
  version: d-my-new-helmrepo-de2b0cb0-v3-202505161014350000
