apiVersion: apps.k8smgmt.io/v3
kind: Workload
metadata:
  name: my-justworkload-1
  project: testing-dileep
spec:
  artifact:
    artifact:
      catalog: default-helm
      chartName: simple-nginx
      chartVersion: 1.1.1
    options:
      maxHistory: 10
      timeout: 5m0s
    type: Helm
  namespace: test
  placement:
    selector: rafay.dev/clusterName=dileep-import
