apiVersion: apps.k8smgmt.io/v3
kind: Workload
metadata:
  name: my-justworkload-1
  project: testing-dileep
spec:
  artifact:
    artifact:
      catalog: default-helm
      chartName: simple-nginx
      chartVersion: 1.1.1
    type: Helm
  namespace: test
