apiVersion: apps.k8smgmt.io/v3
kind: Workload
metadata:
  name: my-workload-16-643a1f69
  project: testing-dileep
spec:
  artifact:
    artifact:
      chartPath:
        name: charts/app
      repository: my-own-helm-git
      revision: master
      valuesPaths:
      - name: values
    options:
      maxHistory: 10
      timeout: 5m0s
    type: Helm
  namespace: test-ns
  placement:
    labels:
    - key: rafay.dev/clusterName
      value: dileep-import
  version: my-workload-16-643a1f69-v2-202505160509540000
