apiVersion: infra.k8smgmt.io/v3
kind: Blueprint
metadata:
  name: latest-bp
  project: testing-dileep
spec:
  base:
    name: minimal
    version: 3.4.0
  customAddons:
  - name: latest-addon-helm-git
    version: "5"
  defaultAddons:
    monitoring:
      gpuOperator: {}
  driftWebhook:
    enabled: true
  type: custom
  version: "5"
  versionState: active
